# Generated by Django 5.1.7 on 2025-04-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_address_alter_user_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1234567890, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(choices=[('junior_scholars', 'Junior Scholars'), ('rising_intellects', 'Rising Intellects'), ('mastermind_elite', 'Mastermind Elite')], default='junior_scholars', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
