# Generated by Django 5.1.7 on 2025-04-04 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_gender_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classsubject'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institute')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('class_subject', 'chapter_number')},
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('class_subject', 'chapter_number'), ('course', 'chapter_number')},
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_subject__isnull', False), ('course__isnull', True)), models.Q(('class_subject__isnull', True), ('course__isnull', False)), _connector='OR'), name='chapter_belongs_to_either_class_subject_or_course'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'teacher', 'institute')},
        ),
    ]
