# Generated by Django manually

from django.db import migrations, models
import django.db.models.deletion


def forward_noop(apps, schema_editor):
    # This operation is intentionally empty - we're just bypassing some problematic migrations
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chapter_class_subject_course_and_more'),
    ]

    operations = [
        # Run a custom operation that does nothing, but marks migration as applied
        migrations.RunPython(forward_noop, migrations.RunPython.noop),
        
        # Create our new CourseMaterial model
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institute')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'unique_together': {('name', 'institute')},
            },
        ),
    ] 