# Generated by Django 5.1.7 on 2025-04-04 08:50

from django.db import migrations, models


def generate_unique_teacher_ids(apps, schema_editor):
    # Get the Teacher model from the migration's app registry
    Teacher = apps.get_model('core', 'Teacher')
    
    # Generate unique IDs for existing teacher records
    for i, teacher in enumerate(Teacher.objects.all()):
        # Use a combination of T + sequential number with padding
        teacher.teacher_id = f'T{(i+1):04d}'  # T0001, T0002, etc.
        teacher.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_and_add_coursematerial'),
    ]

    operations = [
        # First, add the field as nullable to avoid integrity errors
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=10, unique=True, null=True),
        ),
        
        # Then populate it with unique values
        migrations.RunPython(generate_unique_teacher_ids),
        
        # Finally, make it non-nullable
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ] 