# Generated by Django 5.1.7 on 2025-04-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_subject_from_course'),
    ]

    operations = [
    ]
