# Generated by Django 5.1.7 on 2025-04-05 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_chapter_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video'), ('image', 'Image'), ('other', 'Other')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coursematerial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='teacher',
        ),
        migrations.RemoveConstraint(
            model_name='chapter',
            name='chapter_belongs_to_either_class_subject_or_course',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'institute')},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_code',
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1234567890),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_pdfs/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_videos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='changeme123', max_length=128),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(through='core.TeacherSubject', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='chaptermaterial',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.chapter'),
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='class_subject',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
