# Generated by Django 5.1.7 on 2025-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_pdf_video_to_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_pdfs/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_videos/'),
        ),
    ]
