# Generated by Django 5.1.7 on 2025-04-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_pdf_video_to_chapter'),
    ]

    operations = [
    ]
