# Generated by Django 5.1.7 on 2025-04-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fix_chapter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='institute',
            field=models.ForeignKey(default=1234567890, on_delete=django.db.models.deletion.CASCADE, to='core.institute'),
            preserve_default=False,
        ),
    ]
