# Generated by Django 5.1.7 on 2025-04-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_chapter_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermaterial',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='materials',
                to='core.chapter',
                null=True
            ),
        ),
    ]
