# Generated by Django 5.1.7 on 2025-04-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_fix_chapter_material_relation'),
    ]

    operations = [
    ]
