# Generated by Django 5.1.7 on 2025-04-05 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fix_chapter_material_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermaterial',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chapter'),
        ),
    ]
